name: Go

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v cmd/zepto/main.go

    - name: Install Command Line
      run: go get ./cmd/zepto

    - name: Run Zepto CLI - Create project
      run: zepto new blog

    - name: Docker build created zepto project
      uses: docker/build-push-action@v2
      with:
        context: ./blog
        push: false
