name: Go

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v cmd/zepto/main.go

    - name: Install Command Line
      run: go get ./cmd/zepto

    - name: Run Zepto CLI - Create project
      run: zepto new blog

    - name: Cache register
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ hashFiles('blog/**/Dockerfile') }}

    - name: Docker build created zepto project
      uses: docker/build-push-action@v2
      with:
        context: ./blog
        builder: ${{ steps.buildx.outputs.name }}
        load: true
        push: false
        tags: zepto_test_blog:latest
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache

    - name: Run builded docker project
      run: docker run -d -e SESSION_SECRET=app-test -p 8000:8000 zepto_test_blog:latest

    - name: HTTP Health Check
      uses: cygnetdigital/wait_for_response@v2.0.0
      with:
        url: 'http://localhost:8000/health'
        responseCode: '200'
        timeout: 2000
        interval: 500
